#!/bin/bash

function _extra_anonv_help {
    echo "Usage:  anonoei/anonv COMMAND"
    echo ""
    echo "Helper for AnoNV"
    echo ""
    echo "Commands:"
    local ash_arg=(
        "h|help;show_this_message"
        "i|install;install_AnoNV"
        "U|uninstall;uninstall_AnoNV"
        "u|update;update_AnoNV"
        )
    _ash_fmt_help_items "${ash_arg[@]}"
    echo ""
}

function _extra_anonv_install {
    $SHELL <(curl -sS https://raw.githubusercontent.com/anonoei/anonv/main/install.sh) $*
}

function _extra_anonv_uninstall {
    echo "Uninstalling..."
    rm -rf "${HOME}/.config/nvim/lua/anonv"
    echo "AnoNV has been uninstalled!"
}

function _extra_anonv_update {
    old_path=$PWD
    cd ${HOME}/.config/nvim/lua/anonv
    if [[ ! -z $(git fetch --dry-run) ]]; then
        git pull
    fi

    cd $old_path
}

function _extra_anonv_deps {
    if [[ -z "$ASH_ROOT" ]]; then
        source ${HOME}/.local/ash/a.sh
    fi
    case $ASH_PKGMAN in
        pacman)
            ash extra pkg install tar curl git nodejs tree-sitter tree-sitter-cli lazygit ripgrep fd luarocks
            sudo luarocks install jsregexp
            ;;
        *)
            echo "Unsupported package manager: $ASH_PKGMAN"
            exit 1
            ;;
    esac
}

if [[ $# -eq 0 ]]; then
    _extra_anonv_help
    return
fi

ASH_CMD=$1
shift
case $ASH_CMD in
    h|help)
        _extra_anonv_help $*
        ;;
    i|install)
        _extra_anonv_install $*
        ;;
    U|uninstall)
        _extra_anonv_uninstall $*
        ;;
    u|update)
        _extra_anonv_update $*
        ;;
    d|deps)
        _extra_anonv_deps
        ;;
    *)
        _ash_fmt_help_unk "anonv" $ASH_CMD $*
        ;;
esac
